m-cmp/mc-observability

- java/swagger/swagger.yaml
- Update /java/swagger/swagger.yaml
- Add [Insight] Prediction (3 APIs)
- Add [Insight] Anomaly Detection (7 APIs)
- Not currently operational
> Update Insight API Swagger

- java-module/swagger/swagger.yaml
Update Swagger trigger operation id
> Update Swagger operation id

- python/scheduler/airflow-home/dags/anomaly_detection.py
> fix: insight bug fix

- README.md
- python/README.md
> Add python Readme

- java-module/swagger/swagger.yaml
- Fixed model related swagger errors.
> swagger: Define SpiderMonitoringInfo.Data

- java-module/swagger/swagger.yaml
- python/insight/app/api/anomaly/anomaly.py
- python/insight/app/api/anomaly/description/description.py
- python/insight/app/api/anomaly/request/req.py
- python/insight/app/api/prediction/description/description.py
- python/insight/app/api/prediction/prediction.py
- python/insight/app/api/prediction/request/req.py
Python swagger update & bug fix
> Python swagger update

- java-module/README.md
- Add more steps for monitoring setup
> java-module: README.md: Add more monitoring setup guide

- java-module/docker-compose.yaml
- java-module/mc-o11y-manager/src/main/resources/application.yaml
insight service url yaml update
> service url yaml update

- python/README.md
python Readme update
- update API port
> python Readme update

- python/insight/app/api/prediction/description/description.py
- python/insight/app/api/prediction/repo/repo.py
- python/insight/app/api/prediction/response/res.py
- python/insight/app/api/prediction/utils/utils.py
predict API response model update
- 'predicted_value' -> 'value'
> refactor: predict response model update

- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/service/TriggerEventHandlerService.java
> fix:trigger bug fix

- java-module/docker-compose.yaml
- java-module/influxdb_init/init.sh
- python/scheduler/airflow-home/dags/down_sampling.py
- python/scheduler/airflow-home/dags/downsampling_utils/downsampling.py
- python/scheduler/airflow-home/dags/downsampling_utils/multi.py
python: Add scheduler dag for downsampling
> python: Add scheduler dag for downsampling

- .gitignore
- java-module/maria_init.sql
- java-module/swagger/swagger.yaml
- python/insight/app/api/anomaly/description/description.py
- python/insight/app/api/anomaly/model/models.py
- python/insight/app/api/anomaly/repo/repo.py
- python/insight/app/api/anomaly/request/req.py
- python/insight/app/api/anomaly/response/res.py
- python/insight/app/api/anomaly/utils/history.py
- python/insight/app/api/anomaly/utils/setting.py
- python/insight/app/api/anomaly/utils/utils.py
- python/insight/app/api/prediction/description/description.py
- python/insight/app/api/prediction/prediction.py
- python/insight/app/api/prediction/repo/repo.py
- python/insight/app/api/prediction/request/req.py
- python/insight/app/api/prediction/response/res.py
- python/insight/app/api/prediction/utils/utils.py
- python/insight/config/ConfigManager.py
- python/insight/config/config.yaml
- path, query, Res, Req param Update
- mariadb init sql update
- timestamp refactor
> Refactor: python model refactor

- java-module/swagger/swagger.yaml
- python/insight/app/api/anomaly/repo/repo.py
- python/insight/app/api/anomaly/utils/setting.py
- python/insight/app/api/anomaly/utils/utils.py
> swagger & insight bug fix

- java-module/swagger/swagger.yaml
- python/insight/app/api/anomaly/anomaly.py
- python/insight/app/api/anomaly/description/description.py
- python/insight/app/api/anomaly/request/req.py
- python/insight/app/api/anomaly/response/res.py
- python/insight/app/api/anomaly/utils/setting.py
- python/insight/app/api/prediction/description/description.py
- python/insight/app/api/prediction/request/req.py
- python/insight/app/api/prediction/response/res.py
- python/insight/app/api/prediction/utils/utils.py
- python/insight/config/config.yaml
- python model refactor
- python measurement bug fix
- swagger.yaml update
> Refactor: python model refactor & swagger.yaml update

- java-module/mc-o11y-manager/src/main/java/mcmp/mc/observability/mco11ymanager/client/InsightClient.java
- java-module/mc-o11y-manager/src/main/java/mcmp/mc/observability/mco11ymanager/controller/InsightController.java
- python client & controller code update
> fix: python client update

- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/model/TriggerAlertInfo.java
- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/model/TriggerHistoryInfo.java
- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/model/dto/TriggerPolicyUpdateDto.java
- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/service/KapacitorApiService.java
- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/trigger/service/TriggerPolicyAlertService.java
- java-module/mc-o11y-agent/src/main/resources/mailTemplate/TriggerAlertTemplate.html
Update DTO when triggering policy
> Update DTO when triggering policy

- python/insight/app/api/anomaly/utils/history.py
- python/insight/app/api/anomaly/utils/utils.py
- python/insight/app/api/prediction/utils/utils.py
- python/scheduler/airflow-home/dags/down_sampling.py
- python/scheduler/airflow-home/dags/downsampling_utils/multi.py
Python update(metric post api)
> Python update(metric post api)

- java-module/mc-o11y-agent/src/main/java/mcmp/mc/observability/mco11yagent/monitoring/service/OpenSearchService.java
> opensearch query key update

- java-module/swagger/swagger.yaml
- python/insight/app/api/prediction/description/description.py
- python/insight/app/api/prediction/repo/repo.py
- python/insight/app/api/prediction/request/req.py
- python/insight/app/api/prediction/utils/utils.py
- Prediction measurement ENUM update
- system load -> system
- timezone bug fix
> python utils bug fix & swagger update

- java-module/docker-compose.yaml
- java-module/manager-conf/c_1.conf
- java-module/manager-conf/c_2.conf
> feat: add manager logging conf

- python/insight/app/api/anomaly/repo/repo.py
update anomaly timezone kst to utc
> fix: update anomaly timezone kst to utc

- python/insight/app/api/anomaly/anomaly.py
- python/insight/app/api/anomaly/utils/history.py
> fix: anomaly time range bug

- python/scheduler/airflow-home/dags/downsampling_utils/multi.py
> Update downsampling code

- java-module/maria_init.sql
- python/scheduler/airflow-home/dags/anomaly_detection.py
> Update trigger and anomaly

- java-module/manager-conf/c_2.conf
> Update manager conf

- python/insight/app/api/anomaly/response/res.py
- python/insight/app/api/anomaly/utils/setting.py
> Update anomaly model

- java-module/docker-compose.yaml
- python/scheduler/Dockerfile
- python/scheduler/requirements.txt
Update Python docker
- delete volumes
- delete unused code
> Update Python docker

- java-module/docker-compose.yaml
- python/scheduler/airflow-home/airflow.cfg
Change scheduler DB connection url
> Change scheduler DB connection url

- java-module/swagger/swagger.yaml
- python/insight/app/api/log_analysis/log_analysis.py
swagger.yaml updates
- Add Insight Log Analysis API
> feat: Add Insight Log Analysis API

- java-module/docker-compose.yaml
- Fix tumblebug's credential file mount path
> fix: java-module: Fix credential file mount path

- java-module/mc-o11y-manager/src/main/resources/application.yaml
> fix: java-module: Fix merge error

- java-module/docker-compose.yaml
add insight-scheduler depends on mariadb
> add insight-scheduler depends on mariadb

- python/insight/app/api/log_analysis/log_analysis.py
- python/insight/app/api/log_analysis/utils/utils.py
This pull request focuses on improving code readability, consistency, and functionality within the `log_analysis` module. Key changes include reformatting code for better readability, adding new API endpoints for managing OpenAI API keys, and ensuring consistent coding style across the module.
* Reformatted imports in `python/insight/app/api/log_analysis/log_analysis.py` and `python/insight/app/api/log_analysis/utils/utils.py` to align with standard Python conventions. [[1]](diffhunk://#diff-928955a327fe0b3ad1ef062c255f19549c759cf40a32f06c7739163fffa9214dL3-R10) [[2]](diffhunk://#diff-89534988bb6a9dcb11b5159f85dd8fc7462b3d8169ed1e454abbe003a613f79aL1-R1)
* Updated dictionary and string formatting to use consistent styles (e.g., double quotes for strings, inline dictionary definitions). …
> feat: OpenAI key API refactor

- python/insight/app/api/llm_analysis/controller/alert_analysis.py
- python/insight/app/api/llm_analysis/controller/api_key.py
- python/insight/app/api/llm_analysis/controller/llm_model.py
- python/insight/app/api/llm_analysis/controller/llm_session.py
- python/insight/app/api/llm_analysis/controller/log_analysis.py
- python/insight/app/api/llm_analysis/description/alert_analysis.py
- python/insight/app/api/llm_analysis/description/api_key.py
- python/insight/app/api/llm_analysis/description/llm_model.py
- python/insight/app/api/llm_analysis/description/llm_session.py
- python/insight/app/api/llm_analysis/description/log_analysis.py
- python/insight/app/api/llm_analysis/request/req.py
- python/insight/app/core/mcp/mcp_context.py
- python/insight/config/ConfigManager.py
- python/insight/main.py
refactor: Add LLM API descriptions & Update res req models examples
> refactor: Add LLM API descriptions & Update res req models examples

- python/scheduler/Dockerfile
- python/scheduler/requirements.txt
> feat: python: Reduce image size

- java-module/Makefile
- java-module/docker-compose.yaml
- java-module/mc-o11y-manager/src/main/java/com/mcmp/o11ymanager/manager/infrastructure/insight/InsightClient.java
- java-module/mc-o11y-manager/src/main/java/com/mcmp/o11ymanager/manager/infrastructure/port/semaphore/SemaphoreClient.java
- java-module/mc-o11y-manager/src/main/java/com/mcmp/o11ymanager/manager/infrastructure/spider/SpiderClient.java
- java-module/mc-o11y-manager/src/main/resources/application.yaml
- java-module/rabbitmq/etc/rabbitmq.conf
> java-module: Make Docker containers work

- java-module/mc-o11y-manager/src/main/java/com/mcmp/o11ymanager/manager/service/domain/SemaphoreDomainService.java
> fix: java-module: Fix lint warning
